# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Offsetter
                                 A QGIS plugin
 This plugin adds offset a field fpr offset values to line layers to automatically display lines of different categories that are lying on top of each other.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-05-24
        copyright            : (C) 2025 by Suddber
        email                : suddb@posteo.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Suddber'
__date__ = '2025-05-24'
__copyright__ = '(C) 2025 by Suddber'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Offsetter class from file Offsetter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .offsetter import OffsetterPlugin
    return OffsetterPlugin()
