# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Offsetter
                                 A QGIS plugin
 This plugin adds offset a field for offset values to line layers to automatically display lines of different categories that are lying on top of each other.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-05-24
        copyright            : (C) 2025 by Suddber
        email                : suddb@posteo.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Suddber'
__date__ = '2025-05-24'
__copyright__ = '(C) 2025 by Suddber'

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from .offsetter_provider import OffsetterProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class OffsetterPlugin(object):

    def __init__(self):
        self.provider = None

    def initProcessing(self):
        
        self.provider = OffsetterProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
